from __future__ import annotations

from copy import deepcopy
import re
from typing import Any

from .maintenance_windows import synchronize_maintenance_window
from .utils import iso_now, normalize_ticket_id


UPSTREAM_COLUMNS = [
    "SRNo",
    "Problem Summary",
    "Report Date",
    "Customer Contact",
    "Customer Severity",
    "Product",
    "Current Handler",
    "Status",
    "ResolveBy",
    "Resolve By Suspend",
]

LOCAL_COLUMNS = [
    "Planned Date",
    "Site",
    "Cloud",
    "Model",
    "Device",
    "Slot",
    "Part",
    "BOM",
    "Old SN",
    "New SN",
    "RelatedSR",
    "Notes",
    "Spare",
    "Done?",
]

# The first worksheet retains the historical flat columns for compatibility
# and human-readable exports.  Spare-part edits themselves live in the
# normalized ``Spare Parts`` worksheet and ``local.spare_parts`` record.
GENERIC_LOCAL_COLUMNS = [
    "Planned Date",
    "Site",
    "Cloud",
    "RelatedSR",
    "Notes",
    "Done?",
]
LEGACY_SPARE_COLUMNS = [
    "Model",
    "Device",
    "Slot",
    "Part",
    "BOM",
    "Old SN",
    "New SN",
]
EDITABLE_LOCAL_COLUMNS = list(GENERIC_LOCAL_COLUMNS)

SPARE_PARTS_CHANGE_KEY = "Spare Parts"
SPARE_PARTS_SHEET = "Spare Parts"
SPARE_PARTS_EXPORT_MARKER = "Generated by Zeus from the normalized Spare Parts worksheet."
SPARE_PART_COLUMNS = [
    "SRNo",
    "Device #",
    "Device",
    "Model",
    "Part #",
    "Slot",
    "Part",
    "BOM",
    "Faulty SN",
    "New SN",
]

PENDING_COLUMNS = [
    "SRNo",
    "Problem Summary",
    "Planned Date",
    "Site",
    "Cloud",
    "Model",
    "Device",
    "Slot",
    "Part",
    "BOM",
    "Old SN",
    "New SN",
    "RelatedSR",
    "Notes",
    "Report Date",
    "Customer Contact",
    "Customer Severity",
    "Product",
    "Current Handler",
    "Status",
    "ResolveBy",
    "Resolve By Suspend",
    "Spare",
    "Done?",
]

# These two columns occur in the supplied historical Closed workbook.  They
# are recognized legacy aliases, not permission for arbitrary custom columns.
CLOSED_SCHEMA_DRIFT_COLUMNS = ["Old SerialNumber", "New SerialNumber"]

WORKFLOW_CODE_TO_STATE = {
    "N": "not_done",
    "Y": "completed",
    "P": "attempted_issue_pending",
    "?": "unknown_external",
}


def normalize_done(value: Any) -> tuple[str, bool]:
    """Return the normalized workflow code and whether correction occurred."""

    text = str(value).strip().upper() if value is not None else ""
    if text in WORKFLOW_CODE_TO_STATE:
        return text, False
    return "N", True


def spare_from_bom(value: Any) -> str:
    """Return the invariant Spare tag derived from whether BOM has a value."""

    if value is None:
        return "N"
    return "Y" if str(value).strip() else "N"


def _optional_text(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def newline_values(value: Any) -> list[str]:
    """Return unique, non-blank values from a newline-delimited field."""

    supplied = value if isinstance(value, list) else [value]
    candidates = [
        line
        for candidate in supplied
        for line in re.split(r"\r?\n", str(candidate or ""))
    ]
    values: list[str] = []
    seen: set[str] = set()
    for candidate in candidates:
        text = str(candidate or "").strip()
        key = text.casefold()
        if text and key not in seen:
            seen.add(key)
            values.append(text)
    return values


def newline_text(value: Any) -> str | None:
    values = newline_values(value)
    return "\n".join(values) or None


def spare_parts_from_legacy(fields: dict[str, Any] | None) -> list[dict[str, Any]]:
    """Upgrade one historical flat spare record into the normalized shape."""

    values = fields or {}
    device = _optional_text(values.get("Device"))
    model = _optional_text(values.get("Model"))
    part = {
        "slot": newline_text(values.get("Slot")),
        "part": _optional_text(values.get("Part")),
        "bom": _optional_text(values.get("BOM")),
        "new_sn": _optional_text(values.get("New SN")),
        "notes": None,
    }
    has_part = any(value is not None for value in part.values())
    faulty_sns = newline_values(values.get("Old SN"))
    if device is None and model is None and not faulty_sns and not has_part:
        return []
    return [{
        "device_number": 1,
        "device": device,
        "model": model,
        "notes": None,
        "faulty_sns": faulty_sns,
        "next_part_number": 2 if has_part else 1,
        "parts": ([{
            "part_number": 1,
            "submitted_request_ids": [],
            **part,
        }] if has_part else []),
    }]


def normalize_spare_parts(
    value: Any,
    *,
    legacy_fields: dict[str, Any] | None = None,
) -> list[dict[str, Any]]:
    """Return a clean device -> parts hierarchy, upgrading legacy scalars."""

    if value is None:
        return spare_parts_from_legacy(legacy_fields)
    if not isinstance(value, list):
        return []

    devices: list[dict[str, Any]] = []
    used_device_numbers: set[int] = set()
    for device_index, candidate in enumerate(value, start=1):
        if not isinstance(candidate, dict):
            continue
        raw_device_number = candidate.get("device_number", device_index)
        try:
            device_number = int(raw_device_number)
        except (TypeError, ValueError):
            device_number = device_index
        if device_number < 1 or device_number in used_device_numbers:
            device_number = max(used_device_numbers, default=0) + 1
        used_device_numbers.add(device_number)
        device = _optional_text(candidate.get("device"))
        model = _optional_text(candidate.get("model"))
        notes = _optional_text(candidate.get("notes"))
        faulty_sns = newline_values(
            candidate.get("faulty_sns", candidate.get("faulty_sn"))
        )
        faulty_keys = {serial.casefold() for serial in faulty_sns}
        parts: list[dict[str, Any]] = []
        used_part_numbers: set[int] = set()
        raw_parts = candidate.get("parts")
        if isinstance(raw_parts, list):
            for part_index, raw_part in enumerate(raw_parts, start=1):
                if not isinstance(raw_part, dict):
                    continue
                raw_part_number = raw_part.get("part_number", part_index)
                try:
                    part_number = int(raw_part_number)
                except (TypeError, ValueError):
                    part_number = part_index
                if part_number < 1 or part_number in used_part_numbers:
                    part_number = max(used_part_numbers, default=0) + 1
                used_part_numbers.add(part_number)
                # 3.1.4 stored diagnostic serials on each part. Upgrade them
                # into the damaged-device evidence list without losing them.
                for serial in newline_values(
                    raw_part.get("faulty_sns", raw_part.get("faulty_sn"))
                ):
                    if serial.casefold() not in faulty_keys:
                        faulty_sns.append(serial)
                        faulty_keys.add(serial.casefold())
                part = {
                    "part_number": part_number,
                    "slot": newline_text(raw_part.get("slots", raw_part.get("slot"))),
                    "part": _optional_text(raw_part.get("part")),
                    "bom": _optional_text(raw_part.get("bom")),
                    "new_sn": _optional_text(raw_part.get("new_sn")),
                    "notes": _optional_text(raw_part.get("notes")),
                    "submitted_request_ids": [
                        value
                        for value in newline_values(raw_part.get("submitted_request_ids"))
                        if re.fullmatch(r"\d{12}", value)
                    ],
                }
                if any(
                    part.get(key) is not None
                    for key in ("slot", "part", "bom", "new_sn", "notes")
                ) or part["submitted_request_ids"]:
                    parts.append(part)
        raw_next_part = candidate.get("next_part_number")
        try:
            next_part_number = int(raw_next_part)
        except (TypeError, ValueError):
            next_part_number = 1
        next_part_number = max(next_part_number, max(used_part_numbers, default=0) + 1)
        if device is not None or model is not None or notes is not None or faulty_sns or parts:
            devices.append({
                "device_number": device_number,
                "device": device,
                "model": model,
                "notes": notes,
                "faulty_sns": faulty_sns,
                "next_part_number": next_part_number,
                "parts": parts,
            })
    return devices


def spare_part_rows(spare_parts: Any) -> list[dict[str, Any]]:
    """Flatten normalized devices into ordered export rows."""

    rows: list[dict[str, Any]] = []
    for device_index, device in enumerate(normalize_spare_parts(spare_parts), start=1):
        device_number = int(device.get("device_number") or device_index)
        parts = device["parts"] or [None]
        for part_index, part in enumerate(parts, start=1):
            item = part or {}
            part_number = (
                int(item.get("part_number") or part_index)
                if part is not None
                else None
            )
            rows.append(
                {
                    "Device #": device_number,
                    "Device": device.get("device"),
                    "Model": device.get("model"),
                    "Part #": part_number,
                    "Slot": item.get("slot"),
                    "Part": item.get("part"),
                    "BOM": item.get("bom"),
                    "Faulty SN": "\n".join(device.get("faulty_sns") or []) or None,
                    "New SN": item.get("new_sn"),
                }
            )
    return rows


def flat_spare_fields(spare_parts: Any) -> dict[str, Any]:
    """Build the compatibility columns shown on the primary workbook sheet."""

    rows = spare_part_rows(spare_parts)
    mapping = {
        "Model": "Model",
        "Device": "Device",
        "Slot": "Slot",
        "Part": "Part",
        "BOM": "BOM",
        "Old SN": "Faulty SN",
        "New SN": "New SN",
    }
    flattened: dict[str, Any] = {}
    for legacy, normalized in mapping.items():
        values = [row.get(normalized) for row in rows]
        if not values or all(value is None for value in values):
            flattened[legacy] = None
        elif len(values) == 1:
            flattened[legacy] = values[0]
        else:
            flattened[legacy] = "\n".join("" if value is None else str(value) for value in values)
    return flattened


def spare_from_parts(spare_parts: Any) -> str:
    return "Y" if any(row.get("BOM") for row in spare_part_rows(spare_parts)) else "N"


def normalize_local(local: dict[str, Any] | None) -> dict[str, Any]:
    """Return a complete local record with all system-owned invariants applied."""

    prepared = deepcopy(local) if local is not None else {}
    fields = prepared.setdefault("fields", {})
    for column in LOCAL_COLUMNS:
        fields.setdefault(column, None)
    had_spare_parts = "spare_parts" in prepared
    spare_parts = normalize_spare_parts(
        prepared.get("spare_parts") if had_spare_parts else None,
        legacy_fields=None if had_spare_parts else fields,
    )
    prepared["spare_parts"] = spare_parts
    fields.update(flat_spare_fields(spare_parts))
    fields["Spare"] = spare_from_parts(spare_parts)
    prepared = synchronize_maintenance_window(prepared)
    prepared.setdefault("presentation", {"cell_styles": {}})
    prepared.setdefault("mop_fields", {})
    return prepared


def workflow_from_code(value: Any) -> tuple[str, str]:
    code, _ = normalize_done(value)
    return WORKFLOW_CODE_TO_STATE[code], code


def workflow_code(ticket: dict[str, Any]) -> str:
    value = normalize_local(ticket.get("local")).get("fields", {}).get("Done?")
    return normalize_done(value)[0]


def empty_local() -> dict[str, Any]:
    return normalize_local(None)


def empty_email(ticket_id: str) -> dict[str, Any]:
    return {
        "ticket_id": normalize_ticket_id(ticket_id),
        "total_received": 0,
        "total_sent": 0,
        "latest_received_at": None,
        "latest_sent_at": None,
        "last_activity_at": None,
        "last_direction": None,
        "last_fetched_at": None,
        "last_synchronized_at": None,
        "messages": [],
    }


def new_ticket(
    ticket_id: str,
    upstream_fields: dict[str, Any],
    source: dict[str, Any],
    *,
    sr_url: str | None = None,
    local: dict[str, Any] | None = None,
    lifecycle_status: str = "active",
    timestamp: str | None = None,
) -> dict[str, Any]:
    normalized = normalize_ticket_id(ticket_id)
    current_time = timestamp or iso_now()
    fields = {column: upstream_fields.get(column) for column in UPSTREAM_COLUMNS}
    fields["SRNo"] = normalized
    prepared_local = normalize_local(local)
    return {
        "schema_version": 2,
        "ticket_id": normalized,
        "lifecycle": {
            "status": lifecycle_status,
            "first_seen_at": current_time,
            "last_seen_at": current_time,
            "closure_pending_at": None,
            "reopened_at": None,
            "reopen_count": 0,
        },
        "upstream": {
            "source": deepcopy(source),
            "fields": fields,
            "sr_url": sr_url,
        },
        "local": prepared_local,
        "email": empty_email(normalized),
        "mop": {"latest": None, "versions": 0},
        "updated_at": current_time,
    }


def refresh_upstream(
    ticket: dict[str, Any],
    upstream_fields: dict[str, Any],
    source: dict[str, Any],
    *,
    sr_url: str | None,
    timestamp: str | None = None,
) -> dict[str, Any]:
    updated = deepcopy(ticket)
    ticket_id = normalize_ticket_id(updated.get("ticket_id"))
    fields = {column: upstream_fields.get(column) for column in UPSTREAM_COLUMNS}
    fields["SRNo"] = ticket_id
    updated.setdefault("upstream", {})["fields"] = fields
    updated["upstream"]["source"] = deepcopy(source)
    updated["upstream"]["sr_url"] = sr_url
    current_time = timestamp or iso_now()
    updated.setdefault("lifecycle", {})["last_seen_at"] = current_time
    updated["updated_at"] = current_time
    return updated


def notes_cell_value(notes: str) -> str | None:
    cleaned = notes.strip()
    return cleaned or None


def ticket_cell_value(ticket: dict[str, Any], column: str) -> Any:
    if column in UPSTREAM_COLUMNS:
        if column == "SRNo":
            return ticket["ticket_id"]
        return ticket.get("upstream", {}).get("fields", {}).get(column)
    prepared_local = normalize_local(ticket.get("local"))
    local = prepared_local.get("fields", {})
    if column == "Spare":
        return spare_from_parts(prepared_local.get("spare_parts"))
    return local.get(column)
