from __future__ import annotations

from copy import deepcopy
from typing import Any

from .utils import iso_now, normalize_ticket_id


UPSTREAM_COLUMNS = [
    "SRNo",
    "Problem Summary",
    "Report Date",
    "Customer Contact",
    "Customer Severity",
    "Product",
    "Current Handler",
    "Status",
    "ResolveBy",
    "Resolve By Suspend",
]

LOCAL_COLUMNS = [
    "Planned Date",
    "Site",
    "Cloud",
    "Model",
    "Device",
    "Slot",
    "Part",
    "BOM",
    "Old SN",
    "New SN",
    "RelatedSR",
    "Notes",
    "Spare",
    "Done?",
]

# The first worksheet retains the historical flat columns for compatibility
# and human-readable exports.  Spare-part edits themselves live in the
# normalized ``Spare Parts`` worksheet and ``local.spare_parts`` record.
GENERIC_LOCAL_COLUMNS = [
    "Planned Date",
    "Site",
    "Cloud",
    "RelatedSR",
    "Notes",
    "Done?",
]
LEGACY_SPARE_COLUMNS = [
    "Model",
    "Device",
    "Slot",
    "Part",
    "BOM",
    "Old SN",
    "New SN",
]
EDITABLE_LOCAL_COLUMNS = list(GENERIC_LOCAL_COLUMNS)

SPARE_PARTS_CHANGE_KEY = "Spare Parts"
SPARE_PARTS_SHEET = "Spare Parts"
SPARE_PARTS_EXPORT_MARKER = "Generated by Zeus from the normalized Spare Parts worksheet."
SPARE_PART_COLUMNS = [
    "SRNo",
    "Device #",
    "Device",
    "Model",
    "Part #",
    "Slot",
    "Part",
    "BOM",
    "Faulty SN",
    "New SN",
]

PENDING_COLUMNS = [
    "SRNo",
    "Problem Summary",
    "Planned Date",
    "Site",
    "Cloud",
    "Model",
    "Device",
    "Slot",
    "Part",
    "BOM",
    "Old SN",
    "New SN",
    "RelatedSR",
    "Notes",
    "Report Date",
    "Customer Contact",
    "Customer Severity",
    "Product",
    "Current Handler",
    "Status",
    "ResolveBy",
    "Resolve By Suspend",
    "Spare",
    "Done?",
]

# These two columns occur in the supplied historical Closed workbook.  They
# are recognized legacy aliases, not permission for arbitrary custom columns.
CLOSED_SCHEMA_DRIFT_COLUMNS = ["Old SerialNumber", "New SerialNumber"]

WORKFLOW_CODE_TO_STATE = {
    "N": "not_done",
    "Y": "completed",
    "P": "attempted_issue_pending",
    "?": "unknown_external",
}


def normalize_done(value: Any) -> tuple[str, bool]:
    """Return the normalized workflow code and whether correction occurred."""

    text = str(value).strip().upper() if value is not None else ""
    if text in WORKFLOW_CODE_TO_STATE:
        return text, False
    return "N", True


def spare_from_bom(value: Any) -> str:
    """Return the invariant Spare tag derived from whether BOM has a value."""

    if value is None:
        return "N"
    return "Y" if str(value).strip() else "N"


def _optional_text(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def spare_parts_from_legacy(fields: dict[str, Any] | None) -> list[dict[str, Any]]:
    """Upgrade one historical flat spare record into the normalized shape."""

    values = fields or {}
    device = _optional_text(values.get("Device"))
    model = _optional_text(values.get("Model"))
    part = {
        "slot": _optional_text(values.get("Slot")),
        "part": _optional_text(values.get("Part")),
        "bom": _optional_text(values.get("BOM")),
        "faulty_sn": _optional_text(values.get("Old SN")),
        "new_sn": _optional_text(values.get("New SN")),
    }
    has_part = any(value is not None for value in part.values())
    if device is None and model is None and not has_part:
        return []
    return [{"device": device, "model": model, "parts": [part] if has_part else []}]


def normalize_spare_parts(
    value: Any,
    *,
    legacy_fields: dict[str, Any] | None = None,
) -> list[dict[str, Any]]:
    """Return a clean device -> parts hierarchy, upgrading legacy scalars."""

    if value is None:
        return spare_parts_from_legacy(legacy_fields)
    if not isinstance(value, list):
        return []

    devices: list[dict[str, Any]] = []
    for candidate in value:
        if not isinstance(candidate, dict):
            continue
        device = _optional_text(candidate.get("device"))
        model = _optional_text(candidate.get("model"))
        parts: list[dict[str, Any]] = []
        raw_parts = candidate.get("parts")
        if isinstance(raw_parts, list):
            for raw_part in raw_parts:
                if not isinstance(raw_part, dict):
                    continue
                part = {
                    "slot": _optional_text(raw_part.get("slot")),
                    "part": _optional_text(raw_part.get("part")),
                    "bom": _optional_text(raw_part.get("bom")),
                    "faulty_sn": _optional_text(raw_part.get("faulty_sn")),
                    "new_sn": _optional_text(raw_part.get("new_sn")),
                }
                if any(item is not None for item in part.values()):
                    parts.append(part)
        if device is not None or model is not None or parts:
            devices.append({"device": device, "model": model, "parts": parts})
    return devices


def spare_part_rows(spare_parts: Any) -> list[dict[str, Any]]:
    """Flatten normalized devices into ordered export rows."""

    rows: list[dict[str, Any]] = []
    for device_number, device in enumerate(normalize_spare_parts(spare_parts), start=1):
        parts = device["parts"] or [None]
        for part_number, part in enumerate(parts, start=1):
            item = part or {}
            rows.append(
                {
                    "Device #": device_number,
                    "Device": device.get("device"),
                    "Model": device.get("model"),
                    "Part #": part_number if part is not None else None,
                    "Slot": item.get("slot"),
                    "Part": item.get("part"),
                    "BOM": item.get("bom"),
                    "Faulty SN": item.get("faulty_sn"),
                    "New SN": item.get("new_sn"),
                }
            )
    return rows


def flat_spare_fields(spare_parts: Any) -> dict[str, Any]:
    """Build the compatibility columns shown on the primary workbook sheet."""

    rows = spare_part_rows(spare_parts)
    mapping = {
        "Model": "Model",
        "Device": "Device",
        "Slot": "Slot",
        "Part": "Part",
        "BOM": "BOM",
        "Old SN": "Faulty SN",
        "New SN": "New SN",
    }
    flattened: dict[str, Any] = {}
    for legacy, normalized in mapping.items():
        values = [row.get(normalized) for row in rows]
        if not values or all(value is None for value in values):
            flattened[legacy] = None
        elif len(values) == 1:
            flattened[legacy] = values[0]
        else:
            flattened[legacy] = "\n".join("" if value is None else str(value) for value in values)
    return flattened


def spare_from_parts(spare_parts: Any) -> str:
    return "Y" if any(row.get("BOM") for row in spare_part_rows(spare_parts)) else "N"


def normalize_local(local: dict[str, Any] | None) -> dict[str, Any]:
    """Return a complete local record with all system-owned invariants applied."""

    prepared = deepcopy(local) if local is not None else {}
    fields = prepared.setdefault("fields", {})
    for column in LOCAL_COLUMNS:
        fields.setdefault(column, None)
    had_spare_parts = "spare_parts" in prepared
    spare_parts = normalize_spare_parts(
        prepared.get("spare_parts") if had_spare_parts else None,
        legacy_fields=None if had_spare_parts else fields,
    )
    prepared["spare_parts"] = spare_parts
    fields.update(flat_spare_fields(spare_parts))
    fields["Done?"] = normalize_done(fields.get("Done?"))[0]
    fields["Spare"] = spare_from_parts(spare_parts)
    prepared.setdefault("presentation", {"cell_styles": {}})
    prepared.setdefault("mop_fields", {})
    return prepared


def workflow_from_code(value: Any) -> tuple[str, str]:
    code, _ = normalize_done(value)
    return WORKFLOW_CODE_TO_STATE[code], code


def workflow_code(ticket: dict[str, Any]) -> str:
    value = ticket.get("local", {}).get("fields", {}).get("Done?")
    return normalize_done(value)[0]


def empty_local() -> dict[str, Any]:
    return normalize_local(None)


def empty_email(ticket_id: str) -> dict[str, Any]:
    return {
        "ticket_id": normalize_ticket_id(ticket_id),
        "total_received": 0,
        "total_sent": 0,
        "latest_received_at": None,
        "latest_sent_at": None,
        "last_activity_at": None,
        "last_direction": None,
        "last_fetched_at": None,
        "last_synchronized_at": None,
        "messages": [],
    }


def new_ticket(
    ticket_id: str,
    upstream_fields: dict[str, Any],
    source: dict[str, Any],
    *,
    sr_url: str | None = None,
    local: dict[str, Any] | None = None,
    lifecycle_status: str = "active",
    timestamp: str | None = None,
) -> dict[str, Any]:
    normalized = normalize_ticket_id(ticket_id)
    current_time = timestamp or iso_now()
    fields = {column: upstream_fields.get(column) for column in UPSTREAM_COLUMNS}
    fields["SRNo"] = normalized
    prepared_local = normalize_local(local)
    return {
        "schema_version": 2,
        "ticket_id": normalized,
        "lifecycle": {
            "status": lifecycle_status,
            "first_seen_at": current_time,
            "last_seen_at": current_time,
            "closure_pending_at": None,
            "reopened_at": None,
            "reopen_count": 0,
        },
        "upstream": {
            "source": deepcopy(source),
            "fields": fields,
            "sr_url": sr_url,
        },
        "local": prepared_local,
        "email": empty_email(normalized),
        "mop": {"latest": None, "versions": 0},
        "updated_at": current_time,
    }


def refresh_upstream(
    ticket: dict[str, Any],
    upstream_fields: dict[str, Any],
    source: dict[str, Any],
    *,
    sr_url: str | None,
    timestamp: str | None = None,
) -> dict[str, Any]:
    updated = deepcopy(ticket)
    ticket_id = normalize_ticket_id(updated.get("ticket_id"))
    fields = {column: upstream_fields.get(column) for column in UPSTREAM_COLUMNS}
    fields["SRNo"] = ticket_id
    updated.setdefault("upstream", {})["fields"] = fields
    updated["upstream"]["source"] = deepcopy(source)
    updated["upstream"]["sr_url"] = sr_url
    current_time = timestamp or iso_now()
    updated.setdefault("lifecycle", {})["last_seen_at"] = current_time
    updated["updated_at"] = current_time
    return updated


def notes_cell_value(notes: str) -> str | None:
    cleaned = notes.strip()
    return cleaned or None


def ticket_cell_value(ticket: dict[str, Any], column: str) -> Any:
    if column in UPSTREAM_COLUMNS:
        if column == "SRNo":
            return ticket["ticket_id"]
        return ticket.get("upstream", {}).get("fields", {}).get(column)
    prepared_local = normalize_local(ticket.get("local"))
    local = prepared_local.get("fields", {})
    if column == "Spare":
        return spare_from_parts(prepared_local.get("spare_parts"))
    return local.get(column)
